services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: guardianbank
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - guardianbank-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpassword
    depends_on:
      - mysql
    networks:
      - guardianbank-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - guardianbank-network
    restart: unless-stopped

volumes:
  mysql-data:

networks:
  guardianbank-network:
    driver: bridge